<?php
/* Author: Svatopluk Čech */

$labels = [];
$labels['swipeoptions'] = 'Nastavení dotykových gest';
$labels['swipeleft'] = 'Táhnout vlevo';
$labels['swiperight'] = 'Táhnout vpravo';
$labels['swipedown'] = 'Táhnout dolů';
$labels['markasread'] = 'Jako přečtené';
$labels['markasunread'] = 'Jako nepřečtené';
$labels['markasflagged'] = 'Jako označené';
$labels['markasunflagged'] = 'Jako neoznačené';
$labels['deselect'] = 'Zrušit výběr';

$messages = [];
