<?php
/* Author: Sebastian Karlsen <sebastian@fjordmail.no> */

$labels = [];
$labels['swipeoptions'] = 'Swipemuligheder';
$labels['swipeleft'] = 'Venstreswipe';
$labels['swiperight'] = 'Højreswipe';
$labels['swipedown'] = 'Nedoverswipe';
$labels['markasread'] = 'Marker som læst';
$labels['markasunread'] = 'Marker som ulæst';
$labels['markasflagged'] = 'Marker som markeret';
$labels['markasunflagged'] = 'Marker som umarkeret';
$labels['deselect'] = 'Fjern valg';

$messages = [];
