<?php

$labels = array();
$labels['swipeoptions'] = 'Wisch-Optionen';
$labels['swipeleft'] = 'Nach links wischen';
$labels['swiperight'] = 'Nach rechts wischen';
$labels['swipedown'] = 'Nach unten wischen';
$labels['markasread'] = 'Als gelesen markieren';
$labels['markasunread'] = 'Ans ungelesen markieren';
$labels['markasflagged'] = 'Als wichtig markieren';
$labels['markasunflagged'] = 'Als unwichtig markieren';
$labels['deselect'] = 'Abwählen';

$messages = array();
