<?php
/* Author: Philip Weir */

$labels = [];
$labels['swipeoptions'] = 'Swipe options';
$labels['swipeleft'] = 'Swipe left';
$labels['swiperight'] = 'Swipe right';
$labels['swipedown'] = 'Swipe down';
$labels['markasread'] = 'Mark as read';
$labels['markasunread'] = 'Mark as unread';
$labels['markasflagged'] = 'Mark as flagged';
$labels['markasunflagged'] = 'Mark as unflagged';
$labels['deselect'] = 'Deselect';

$messages = [];
