<?php
/* Author: Sebastian Karlsen <sebastian@corp.inbox.com> */

$labels = [];
$labels['swipeoptions'] = 'Kerimisvalikud';
$labels['swipeleft'] = 'Kerige vasakule';
$labels['swiperight'] = 'Kerige paremale';
$labels['swipedown'] = 'Kerige alla';
$labels['markasread'] = 'Märgi loetuks';
$labels['markasunread'] = 'Märgi lugemataks';
$labels['markasflagged'] = 'Märgi lipuga';
$labels['markasunflagged'] = 'Märgi ilma liputa';
$labels['deselect'] = 'Tühista valik';

$messages = [];
