<?php
/* Author: Sebastian Karlsen <sebastian@fjordmail.no> */

$labels = [];
$labels['swipeoptions'] = 'Pyyhkäisy asetukset';
$labels['swipeleft'] = 'Pyyhkäisy vasemmalle';
$labels['swiperight'] = 'Pyyhkäisy oikealle';
$labels['swipedown'] = 'Pyyhkäisy alas';
$labels['markasread'] = 'Merkitse luetuksi';
$labels['markasunread'] = 'Merkitse lukemattomaksi';
$labels['markasflagged'] = 'Merkitse lipulla';
$labels['markasunflagged'] = 'Merkitse liputtomaksi';
$labels['deselect'] = 'Poista valinta';

$messages = [];
