<?php
/* Author: Sebastian Karlsen <sebastian@fjordmail.no> */

$labels = [];
$labels['swipeoptions'] = 'Csúsztatási lehetőségek lapozáshoz';
$labels['swipeleft'] = 'Csúsztatás balra';
$labels['swiperight'] = 'Csúsztatás jobbra';
$labels['swipedown'] = 'Csúsztatás lefelé';
$labels['markasread'] = 'Megjelölés olvasottként';
$labels['markasunread'] = 'Megjelölés olvasatlanként';
$labels['markasflagged'] = 'Megjelölés kiemeltként';
$labels['markasunflagged'] = 'Kiemelt megjelölés törlése';
$labels['deselect'] = 'Kiválasztás törlése';

$messages = [];
