<?php
/* Author: Sebastian Karlsen <sebastian@fjordmail.no> */

$labels = [];
$labels['swipeoptions'] = 'Sveipeinnstillinger';
$labels['swipeleft'] = 'Venstresveip';
$labels['swiperight'] = 'Høyresveip';
$labels['swipedown'] = 'Nedoversveip';
$labels['markasread'] = 'Merk som lest';
$labels['markasunread'] = 'Merk som ulest';
$labels['markasflagged'] = 'Merk som flagget';
$labels['markasunflagged'] = 'Merk som uflagget';
$labels['deselect'] = 'Fjern valget';

$messages = [];
