<?php
/* Author: fvdm */

$labels = [];
$labels['swipeoptions'] = 'Veegopties';
$labels['swipeleft'] = 'Veeg naar links';
$labels['swiperight'] = 'Veeg naar rechts';
$labels['swipedown'] = 'Veeg omlaag';
$labels['markasread'] = 'Markeer als gelezen';
$labels['markasunread'] = 'Markeer als ongelezen';
$labels['markasflagged'] = 'Markeren';
$labels['markasunflagged'] = 'Niet-markeren';
$labels['deselect'] = 'Deselecteren';

$messages = [];
