<?php
/* Author: Luís Neto */

$labels = [];
$labels['swipeoptions'] = 'Opções de deslize';
$labels['swipeleft'] = 'Deslizar para a esquerda';
$labels['swiperight'] = 'Deslizar para a direita';
$labels['swipedown'] = 'Deslizar para baixo';
$labels['markasread'] = 'Marcar como lida';
$labels['markasunread'] = 'Marcar como não lida';
$labels['markasflagged'] = 'Marcar como sinalizado';
$labels['markasunflagged'] = 'Marcar como não sinalizado';
$labels['deselect'] = 'Desselecionar';

$messages = [];
