<?php
/* Author: Sebastian Karlsen <sebastian@corp.inbox.com> */

$labels = [];
$labels['swipeoptions'] = 'Варианты прокрутки';
$labels['swipeleft'] = 'Прокрутить влево';
$labels['swiperight'] = 'Прокрутить вправо';
$labels['swipedown'] = 'Прокрутить вниз';
$labels['markasread'] = 'Отметить как прочитанное';
$labels['markasunread'] = 'Отметить как непрочитанное';
$labels['markasflagged'] = 'Отметить как помеченное';
$labels['markasunflagged'] = 'Отметить как непомеченное';
$labels['deselect'] = 'Отменить выделение';

$messages = [];
